In [27]:
import os
import nibabel as nib
import matplotlib
import mrivis
import scipy
import numpy as np
import nilearn
import sklearn

In [43]:
import pandas as pd

In [34]:
!pip install --no-cache-dir nobrainer

Collecting nobrainer
  Downloading nobrainer-0.0.3-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 474 kB/s eta 0:00:01
Requirement already satisfied: numpy in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from nobrainer) (1.20.3)
Collecting tensorflow-probability>=0.7.0
  Downloading tensorflow_probability-0.12.2-py2.py3-none-any.whl (4.8 MB)
     |████████████████████████████████| 4.8 MB 1.3 MB/s eta 0:00:01
Requirement already satisfied: nibabel in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from nobrainer) (3.2.1)
Collecting scikit-image
  Downloading scikit_image-0.18.1-cp39-cp39-manylinux1_x86_64.whl (28.9 MB)
     |████████████████████████████████| 28.9 MB 443 kB/s eta 0:00:01
Requirement already satisfied: click in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from nobrainer) (8.0.1)
Requirement already satisfied: decorator in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorflow-probability>=0.7.0->nobrainer) (4.4.2)
Requirement already satisfied: six>=1.10.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorflow-probability>=0.7.0->nobrainer) (1.15.0)
Collecting cloudpickle>=1.3
  Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting dm-tree
  Downloading dm_tree-0.1.6-cp39-cp39-manylinux_2_24_x86_64.whl (94 kB)
     |████████████████████████████████| 94 kB 641 kB/s eta 0:00:01
Collecting gast>=0.3.2
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: packaging>=14.3 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from nibabel->nobrainer) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from packaging>=14.3->nibabel->nobrainer) (2.4.7)
Collecting networkx>=2.0
  Downloading networkx-2.5.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 431 kB/s eta 0:00:01     |█████████████████████           | 1.1 MB 975 kB/s eta 0:00:01
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from scikit-image->nobrainer) (8.2.0)
Collecting imageio>=2.3.0
  Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 619 kB/s eta 0:00:01
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.1.1-cp39-cp39-manylinux1_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 995 kB/s eta 0:00:01
Requirement already satisfied: scipy>=1.0.1 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from scikit-image->nobrainer) (1.6.3)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from scikit-image->nobrainer) (3.4.2)
Collecting tifffile>=2019.7.26
  Downloading tifffile-2021.6.14-py3-none-any.whl (169 kB)
     |████████████████████████████████| 169 kB 667 kB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->nobrainer) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->nobrainer) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->nobrainer) (0.10.0)
Installing collected packages: tifffile, PyWavelets, networkx, imageio, gast, dm-tree, cloudpickle, tensorflow-probability, scikit-image, nobrainer
Successfully installed PyWavelets-1.1.1 cloudpickle-1.6.0 dm-tree-0.1.6 gast-0.4.0 imageio-2.9.0 networkx-2.5.1 nobrainer-0.0.3 scikit-image-0.18.1 tensorflow-probability-0.12.2 tifffile-2021.6.14

In [36]:
!pip install --no-cache-dir tensorflow

Collecting tensorflow
  Downloading tensorflow-2.5.0-cp39-cp39-manylinux2010_x86_64.whl (454.4 MB)
     |████████████████████████████████| 454.4 MB 2.8 MB/s eta 0:00:011   |█████▏                          | 72.9 MB 453 kB/s eta 0:14:01     |██████████▉                     | 154.3 MB 250 kB/s eta 0:20:01     |████████████▊                   | 180.2 MB 4.2 MB/s eta 0:01:05     |█████████████                   | 185.9 MB 1.9 MB/s eta 0:02:20     |█████████████                   | 186.1 MB 1.9 MB/s eta 0:02:20     |██████████████▏                 | 201.1 MB 3.5 MB/s eta 0:01:13     |████████████████▎               | 230.5 MB 213 kB/s eta 0:17:31     |██████████████████▎             | 260.3 MB 552 kB/s eta 0:05:52     |███████████████████▋            | 278.2 MB 9.8 MB/s eta 0:00:19     |████████████████████▊           | 294.8 MB 463 kB/s eta 0:05:45     |██████████████████████▍         | 317.5 MB 6.5 MB/s eta 0:00:22     |███████████████████████         | 327.4 MB 225 kB/s eta 0:09:23     |█████████████████████████▍      | 360.8 MB 99 kB/s eta 0:15:37     |█████████████████████████████▏  | 414.5 MB 1.6 MB/s eta 0:00:25     |█████████████████████████████▉  | 424.4 MB 2.1 MB/s eta 0:00:15     |██████████████████████████████▋ | 434.8 MB 1.2 MB/s eta 0:00:16     |██████████████████████████████▊ | 435.9 MB 1.3 MB/s eta 0:00:15     |███████████████████████████████▊| 451.2 MB 313 kB/s eta 0:00:11
Requirement already satisfied: six~=1.15.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: wheel~=0.35 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorflow) (0.36.2)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/grpcio/
Collecting grpcio~=1.34.0
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/1f/a8/ba1a3db9c1db9658d851aa4de673b6cb2a6de9429fe9867033d634dcfe51/grpcio-1.34.1-cp39-cp39-manylinux2014_x86_64.whl
  Downloading grpcio-1.34.1-cp39-cp39-manylinux2014_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 774 kB/s eta 0:00:01     |███████████████████████████▌    | 3.4 MB 751 kB/s eta 0:00:01
Requirement already satisfied: wrapt~=1.12.1 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorflow) (1.12.1)
Collecting h5py~=3.1.0
  Downloading h5py-3.1.0-cp39-cp39-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 882 kB/s eta 0:00:01     |███████████████████████████▍    | 3.7 MB 690 kB/s eta 0:00:01
Collecting astunparse~=1.6.3
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting termcolor~=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting absl-py~=0.10
  Downloading absl_py-0.13.0-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 629 kB/s eta 0:00:01
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting keras-nightly~=2.5.0.dev
  Downloading keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 493 kB/s eta 0:00:01
Collecting protobuf>=3.9.2
  Downloading protobuf-3.17.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 776 kB/s eta 0:00:01
Requirement already satisfied: gast==0.4.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorflow) (0.4.0)
Collecting tensorboard~=2.5
  Downloading tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
     |████████████████████████████████| 6.0 MB 559 kB/s eta 0:00:01     |███████████████████████▍        | 4.4 MB 297 kB/s eta 0:00:06
Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
  Downloading tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
     |████████████████████████████████| 462 kB 566 kB/s eta 0:00:01
Collecting opt-einsum~=3.3.0
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 489 kB/s eta 0:00:01
Collecting google-pasta~=0.2
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 476 kB/s eta 0:00:01
Collecting keras-preprocessing~=1.1.2
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 789 kB/s eta 0:00:01
Collecting numpy~=1.19.2
  Downloading numpy-1.19.5-cp39-cp39-manylinux2010_x86_64.whl (14.9 MB)
     |████████████████████████████████| 14.9 MB 555 kB/s eta 0:00:01     |██████████████████████          | 10.3 MB 480 kB/s eta 0:00:10
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: requests<3,>=2.21.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow) (2.24.0)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: setuptools>=41.0.0 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow) (52.0.0.post20210125)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 574 kB/s eta 0:00:01
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
     |████████████████████████████████| 781 kB 290 kB/s eta 0:00:01
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.31.0-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 447 kB/s eta 0:00:01
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 323 kB/s eta 0:00:01
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
     |████████████████████████████████| 4.9 MB 390 kB/s eta 0:00:01     |███████████████████████████████▏| 4.8 MB 390 kB/s eta 0:00:01
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 600 kB/s eta 0:00:01    |████▏                           | 20 kB 453 kB/s eta 0:00:01
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 380 kB/s eta 0:00:01
Requirement already satisfied: idna<3,>=2.5 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (1.25.11)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)

     |████████████████████████████████| 146 kB 394 kB/s eta 0:00:01
Building wheels for collected packages: termcolor
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=4b91ec85e09bf38ab0483a08b5dfa7a962a9277db82986e182b72bb46877ac9b
  Stored in directory: /tmp/pip-ephem-wheel-cache-tn7rf1ei/wheels/b6/0d/90/0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor
Installing collected packages: pyasn1, rsa, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, werkzeug, tensorboard-plugin-wit, tensorboard-data-server, protobuf, numpy, markdown, grpcio, google-auth-oauthlib, absl-py, typing-extensions, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras-nightly, h5py, google-pasta, flatbuffers, astunparse, tensorflow
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
Successfully installed absl-py-0.13.0 astunparse-1.6.3 cachetools-4.2.2 flatbuffers-1.12 google-auth-1.31.0 google-auth-oauthlib-0.4.4 google-pasta-0.2.0 grpcio-1.34.1 h5py-3.1.0 keras-nightly-2.5.0.dev2021032900 keras-preprocessing-1.1.2 markdown-3.3.4 numpy-1.19.5 oauthlib-3.1.1 opt-einsum-3.3.0 protobuf-3.17.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 rsa-4.7.2 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.5.0 tensorflow-estimator-2.5.0 termcolor-1.1.0 typing-extensions-3.7.4.3 werkzeug-2.0.1

In [37]:
import nobrainer

### get started with nobrainer

In [40]:
csv_path = nobrainer.utils.get_data()

Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-01/mri/t1.mgz
4276224/4268641 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-01/mri/aparc+aseg.mgz
344064/339508 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-02/mri/t1.mgz
3366912/3360239 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-02/mri/aparc+aseg.mgz
360448/354161 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-03/mri/t1.mgz
3907584/3900552 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-03/mri/aparc+aseg.mgz
352256/350451 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-04/mri/t1.mgz
5120000/5115676 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-04/mri/aparc+aseg.mgz
425984/419833 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-05/mri/t1.mgz
4743168/4738958 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-05/mri/aparc+aseg.mgz
417792/417547 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-06/mri/t1.mgz
4964352/4956283 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-06/mri/aparc+aseg.mgz
409600/403496 [==============================] - 1s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-07/mri/t1.mgz
4276224/4271015 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-07/mri/aparc+aseg.mgz
360448/356833 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-08/mri/t1.mgz
4702208/4702059 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-08/mri/aparc+aseg.mgz
417792/414228 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-09/mri/t1.mgz
4227072/4220278 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-09/mri/aparc+aseg.mgz
401408/395977 [==============================] - 0s 1us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-10/mri/t1.mgz
3874816/3868870 [==============================] - 1s 0us/step
Downloading data from https://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/sub-10/mri/aparc+aseg.mgz
335872/335557 [==============================] - 0s 1us/step

In [41]:
!head $csv_path

### convert json to csv

In [49]:
wd = '/home/doehlerj/Dokumente/brainhack2021/'
os.chdir(wd)

In [97]:
raw_data_path = 'data_rawBIDS'
mriqc_data_path = 'data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w'

#raw_filename = os.path.join(raw_data_path, 'BMB/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.nii.gz')
#mriqc_filename = os.path.join(mriqc_data_path, '.json')

#mriqc_filename
os.getcwd()

pdObj = pd.read_json(mriqc_data_path + '.json')

pdObj.head()

'/home/doehlerj/Dokumente/brainhack2021'

In [76]:
pdObj.columns

Index(['bids_meta', 'cjv', 'cnr', 'efc', 'fber', 'fwhm_avg', 'fwhm_x',
       'fwhm_y', 'fwhm_z', 'icvs_csf', 'icvs_gm', 'icvs_wm', 'inu_med',
       'inu_range', 'provenance', 'qi_1', 'qi_2', 'rpve_csf', 'rpve_gm',
       'rpve_wm', 'size_x', 'size_y', 'size_z', 'snr_csf', 'snr_gm',
       'snr_total', 'snr_wm', 'snrd_csf', 'snrd_gm', 'snrd_total', 'snrd_wm',
       'spacing_x', 'spacing_y', 'spacing_z', 'summary_bg_k', 'summary_bg_mad',
       'summary_bg_mean', 'summary_bg_median', 'summary_bg_n',
       'summary_bg_p05', 'summary_bg_p95', 'summary_bg_stdv', 'summary_csf_k',
       'summary_csf_mad', 'summary_csf_mean', 'summary_csf_median',
       'summary_csf_n', 'summary_csf_p05', 'summary_csf_p95',
       'summary_csf_stdv', 'summary_gm_k', 'summary_gm_mad', 'summary_gm_mean',
       'summary_gm_median', 'summary_gm_n', 'summary_gm_p05', 'summary_gm_p95',
       'summary_gm_stdv', 'summary_wm_k', 'summary_wm_mad', 'summary_wm_mean',
       'summary_wm_median', 'summary_wm_n', 'summary_wm_p05', 'summary_wm_p95',
       'summary_wm_stdv', 'tpm_overlap_csf', 'tpm_overlap_gm',
       'tpm_overlap_wm', 'wm2max'],
      dtype='object')

In [81]:
qc_metrics = ['cjv', 'cnr', 'efc', 'fber', 'fwhm_avg', 'fwhm_x',
       'fwhm_y', 'fwhm_z', 'icvs_csf', 'icvs_gm', 'icvs_wm', 'inu_med',
       'inu_range', 'qi_1', 'qi_2', 'rpve_csf', 'rpve_gm',
       'rpve_wm','snr_csf', 'snr_gm',
       'snr_total', 'snr_wm', 'snrd_csf', 'snrd_gm', 'snrd_total', 'snrd_wm',
       'summary_bg_k', 'summary_bg_mad',
       'summary_bg_mean', 'summary_bg_median', 'summary_bg_n',
       'summary_bg_p05', 'summary_bg_p95', 'summary_bg_stdv', 'summary_csf_k',
       'summary_csf_mad', 'summary_csf_mean', 'summary_csf_median',
       'summary_csf_n', 'summary_csf_p05', 'summary_csf_p95',
       'summary_csf_stdv', 'summary_gm_k', 'summary_gm_mad', 'summary_gm_mean',
       'summary_gm_median', 'summary_gm_n', 'summary_gm_p05', 'summary_gm_p95',
       'summary_gm_stdv', 'summary_wm_k', 'summary_wm_mad', 'summary_wm_mean',
       'summary_wm_median', 'summary_wm_n', 'summary_wm_p05', 'summary_wm_p95',
       'summary_wm_stdv', 'tpm_overlap_csf', 'tpm_overlap_gm',
       'tpm_overlap_wm', 'wm2max']

In [82]:
df_new = pdObj[qc_metrics]

In [84]:
df_new = df_new.reset_index(drop=True)
df_new = df_new.iloc[0,:]

In [85]:
df_new

cjv                  0.401860
cnr                  3.208962
efc                  0.580837
fber               390.788391
fwhm_avg             3.238950
                      ...
summary_wm_stdv     60.054348
tpm_overlap_csf      0.194286
tpm_overlap_gm       0.491109
tpm_overlap_wm       0.556597
wm2max               0.498310
Name: 0, Length: 62, dtype: float64

In [ ]:
df_new.to_csv(mriqc_data_path + '.csv')

### iterate over all subjects and files

In [99]:
subject_list = ['sub-00030{:0>2d}'.format(i) for i in range(1,65)]

In [102]:
def convert_json_to_csv(filename):
    df = pd.read_json(json_file + '.json')
    #df_new = df[qc_metrics]
    df = df.reset_index(drop=True)
    df = df.iloc[0,:] 
    df.to_csv(json_file + '.csv')

In [103]:
import glob

wd = '/home/doehlerj/Dokumente/brainhack2021'
os.chdir(wd)

path_data = 'data_mriqc'
for subj in subject_list:
    print('Processing ', subj)
    session='ses-1'
    for mri in ['anat','func']:
        if mri == 'anat':
            json_file_name = '{}_{}_run-1_T1w'.format(subj,session)
            json_file = os.path.join(path_data,subj,session,mri,json_file_name)
            try:
                convert_json_to_csv(filename)
                print('Converted successfully ', json_file)
            except:
                print('File not found ', json_file)
        else:
            files = glob.glob(os.path.join(path_data,subj,session,mri)+'/*.json')
            for j in range(1,len(files)+1):
                json_file_name = '{}_{}_task-rest_run-{}_bold'.format(subj,session,j)
                json_file = os.path.join(path_data,subj,session,mri,json_file_name)
                try:
                    convert_json_to_csv(filename)
                    print('Converted successfully ', json_file)
                except:
                    print('File not found ', json_file)

Processing  sub-0003001
Converted successfully  data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003001/ses-1/func/sub-0003001_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003001/ses-1/func/sub-0003001_ses-1_task-rest_run-2_bold
Processing  sub-0003002
Converted successfully  data_mriqc/sub-0003002/ses-1/anat/sub-0003002_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003002/ses-1/func/sub-0003002_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003002/ses-1/func/sub-0003002_ses-1_task-rest_run-2_bold
Processing  sub-0003003
File not found  data_mriqc/sub-0003003/ses-1/anat/sub-0003003_ses-1_run-1_T1w
Processing  sub-0003004
Converted successfully  data_mriqc/sub-0003004/ses-1/anat/sub-0003004_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003004/ses-1/func/sub-0003004_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003004/ses-1/func/sub-0003004_ses-1_task-rest_run-2_bold
Processing  sub-0003005
File not found  data_mriqc/sub-0003005/ses-1/anat/sub-0003005_ses-1_run-1_T1w
Processing  sub-0003006
Converted successfully  data_mriqc/sub-0003006/ses-1/anat/sub-0003006_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003006/ses-1/func/sub-0003006_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003006/ses-1/func/sub-0003006_ses-1_task-rest_run-2_bold
Processing  sub-0003007
Converted successfully  data_mriqc/sub-0003007/ses-1/anat/sub-0003007_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003007/ses-1/func/sub-0003007_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003007/ses-1/func/sub-0003007_ses-1_task-rest_run-2_bold
Processing  sub-0003008
Converted successfully  data_mriqc/sub-0003008/ses-1/anat/sub-0003008_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003008/ses-1/func/sub-0003008_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003008/ses-1/func/sub-0003008_ses-1_task-rest_run-2_bold
Processing  sub-0003009
Converted successfully  data_mriqc/sub-0003009/ses-1/anat/sub-0003009_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003009/ses-1/func/sub-0003009_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003009/ses-1/func/sub-0003009_ses-1_task-rest_run-2_bold
Processing  sub-0003010
Converted successfully  data_mriqc/sub-0003010/ses-1/anat/sub-0003010_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003010/ses-1/func/sub-0003010_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003010/ses-1/func/sub-0003010_ses-1_task-rest_run-2_bold
Processing  sub-0003011
Converted successfully  data_mriqc/sub-0003011/ses-1/anat/sub-0003011_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003011/ses-1/func/sub-0003011_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003011/ses-1/func/sub-0003011_ses-1_task-rest_run-2_bold
Processing  sub-0003012
Converted successfully  data_mriqc/sub-0003012/ses-1/anat/sub-0003012_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003012/ses-1/func/sub-0003012_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003012/ses-1/func/sub-0003012_ses-1_task-rest_run-2_bold
Processing  sub-0003013
Converted successfully  data_mriqc/sub-0003013/ses-1/anat/sub-0003013_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003013/ses-1/func/sub-0003013_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003013/ses-1/func/sub-0003013_ses-1_task-rest_run-2_bold
Processing  sub-0003014
Converted successfully  data_mriqc/sub-0003014/ses-1/anat/sub-0003014_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003014/ses-1/func/sub-0003014_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003014/ses-1/func/sub-0003014_ses-1_task-rest_run-2_bold
Processing  sub-0003015
Converted successfully  data_mriqc/sub-0003015/ses-1/anat/sub-0003015_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003015/ses-1/func/sub-0003015_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003015/ses-1/func/sub-0003015_ses-1_task-rest_run-2_bold
Processing  sub-0003016
Converted successfully  data_mriqc/sub-0003016/ses-1/anat/sub-0003016_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003016/ses-1/func/sub-0003016_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003016/ses-1/func/sub-0003016_ses-1_task-rest_run-2_bold
Processing  sub-0003017
Converted successfully  data_mriqc/sub-0003017/ses-1/anat/sub-0003017_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003017/ses-1/func/sub-0003017_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003017/ses-1/func/sub-0003017_ses-1_task-rest_run-2_bold
Processing  sub-0003018
Converted successfully  data_mriqc/sub-0003018/ses-1/anat/sub-0003018_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003018/ses-1/func/sub-0003018_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003018/ses-1/func/sub-0003018_ses-1_task-rest_run-2_bold
Processing  sub-0003019
File not found  data_mriqc/sub-0003019/ses-1/anat/sub-0003019_ses-1_run-1_T1w
Processing  sub-0003020
Converted successfully  data_mriqc/sub-0003020/ses-1/anat/sub-0003020_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003020/ses-1/func/sub-0003020_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003020/ses-1/func/sub-0003020_ses-1_task-rest_run-2_bold
Processing  sub-0003021
Converted successfully  data_mriqc/sub-0003021/ses-1/anat/sub-0003021_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003021/ses-1/func/sub-0003021_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003021/ses-1/func/sub-0003021_ses-1_task-rest_run-2_bold
Processing  sub-0003022
Converted successfully  data_mriqc/sub-0003022/ses-1/anat/sub-0003022_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003022/ses-1/func/sub-0003022_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003022/ses-1/func/sub-0003022_ses-1_task-rest_run-2_bold
Processing  sub-0003023
Converted successfully  data_mriqc/sub-0003023/ses-1/anat/sub-0003023_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003023/ses-1/func/sub-0003023_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003023/ses-1/func/sub-0003023_ses-1_task-rest_run-2_bold
Processing  sub-0003024
Converted successfully  data_mriqc/sub-0003024/ses-1/anat/sub-0003024_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003024/ses-1/func/sub-0003024_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003024/ses-1/func/sub-0003024_ses-1_task-rest_run-2_bold
Processing  sub-0003025
Converted successfully  data_mriqc/sub-0003025/ses-1/anat/sub-0003025_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003025/ses-1/func/sub-0003025_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003025/ses-1/func/sub-0003025_ses-1_task-rest_run-2_bold
Processing  sub-0003026
Converted successfully  data_mriqc/sub-0003026/ses-1/anat/sub-0003026_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003026/ses-1/func/sub-0003026_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003026/ses-1/func/sub-0003026_ses-1_task-rest_run-2_bold
Processing  sub-0003027
File not found  data_mriqc/sub-0003027/ses-1/anat/sub-0003027_ses-1_run-1_T1w
Processing  sub-0003028
File not found  data_mriqc/sub-0003028/ses-1/anat/sub-0003028_ses-1_run-1_T1w
Processing  sub-0003029
File not found  data_mriqc/sub-0003029/ses-1/anat/sub-0003029_ses-1_run-1_T1w
Processing  sub-0003030
File not found  data_mriqc/sub-0003030/ses-1/anat/sub-0003030_ses-1_run-1_T1w
Processing  sub-0003031
File not found  data_mriqc/sub-0003031/ses-1/anat/sub-0003031_ses-1_run-1_T1w
Processing  sub-0003032
Converted successfully  data_mriqc/sub-0003032/ses-1/anat/sub-0003032_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003032/ses-1/func/sub-0003032_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003032/ses-1/func/sub-0003032_ses-1_task-rest_run-2_bold
Processing  sub-0003033
Converted successfully  data_mriqc/sub-0003033/ses-1/anat/sub-0003033_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003033/ses-1/func/sub-0003033_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003033/ses-1/func/sub-0003033_ses-1_task-rest_run-2_bold
Processing  sub-0003034
Converted successfully  data_mriqc/sub-0003034/ses-1/anat/sub-0003034_ses-1_run-1_T1w

Converted successfully  data_mriqc/sub-0003034/ses-1/func/sub-0003034_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003034/ses-1/func/sub-0003034_ses-1_task-rest_run-2_bold
Processing  sub-0003035
File not found  data_mriqc/sub-0003035/ses-1/anat/sub-0003035_ses-1_run-1_T1w
Processing  sub-0003036
File not found  data_mriqc/sub-0003036/ses-1/anat/sub-0003036_ses-1_run-1_T1w
Processing  sub-0003037
Converted successfully  data_mriqc/sub-0003037/ses-1/anat/sub-0003037_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003037/ses-1/func/sub-0003037_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003037/ses-1/func/sub-0003037_ses-1_task-rest_run-2_bold
Processing  sub-0003038
Converted successfully  data_mriqc/sub-0003038/ses-1/anat/sub-0003038_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003038/ses-1/func/sub-0003038_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003038/ses-1/func/sub-0003038_ses-1_task-rest_run-2_bold
Processing  sub-0003039
Converted successfully  data_mriqc/sub-0003039/ses-1/anat/sub-0003039_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003039/ses-1/func/sub-0003039_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003039/ses-1/func/sub-0003039_ses-1_task-rest_run-2_bold
Processing  sub-0003040
Converted successfully  data_mriqc/sub-0003040/ses-1/anat/sub-0003040_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003040/ses-1/func/sub-0003040_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003040/ses-1/func/sub-0003040_ses-1_task-rest_run-2_bold
Processing  sub-0003041
Converted successfully  data_mriqc/sub-0003041/ses-1/anat/sub-0003041_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003041/ses-1/func/sub-0003041_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003041/ses-1/func/sub-0003041_ses-1_task-rest_run-2_bold
Processing  sub-0003042
Converted successfully  data_mriqc/sub-0003042/ses-1/anat/sub-0003042_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003042/ses-1/func/sub-0003042_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003042/ses-1/func/sub-0003042_ses-1_task-rest_run-2_bold
Processing  sub-0003043
File not found  data_mriqc/sub-0003043/ses-1/anat/sub-0003043_ses-1_run-1_T1w
Processing  sub-0003044
Converted successfully  data_mriqc/sub-0003044/ses-1/anat/sub-0003044_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003044/ses-1/func/sub-0003044_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003044/ses-1/func/sub-0003044_ses-1_task-rest_run-2_bold
Processing  sub-0003045
Converted successfully  data_mriqc/sub-0003045/ses-1/anat/sub-0003045_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003045/ses-1/func/sub-0003045_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003045/ses-1/func/sub-0003045_ses-1_task-rest_run-2_bold
Processing  sub-0003046
File not found  data_mriqc/sub-0003046/ses-1/anat/sub-0003046_ses-1_run-1_T1w
Processing  sub-0003047
Converted successfully  data_mriqc/sub-0003047/ses-1/anat/sub-0003047_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003047/ses-1/func/sub-0003047_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003047/ses-1/func/sub-0003047_ses-1_task-rest_run-2_bold
Processing  sub-0003048
File not found  data_mriqc/sub-0003048/ses-1/anat/sub-0003048_ses-1_run-1_T1w
Processing  sub-0003049
Converted successfully  data_mriqc/sub-0003049/ses-1/anat/sub-0003049_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003049/ses-1/func/sub-0003049_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003049/ses-1/func/sub-0003049_ses-1_task-rest_run-2_bold
Processing  sub-0003050
Converted successfully  data_mriqc/sub-0003050/ses-1/anat/sub-0003050_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003050/ses-1/func/sub-0003050_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003050/ses-1/func/sub-0003050_ses-1_task-rest_run-2_bold
Processing  sub-0003051
Converted successfully  data_mriqc/sub-0003051/ses-1/anat/sub-0003051_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-4_bold
Processing  sub-0003052
Converted successfully  data_mriqc/sub-0003052/ses-1/anat/sub-0003052_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-4_bold
Processing  sub-0003053
File not found  data_mriqc/sub-0003053/ses-1/anat/sub-0003053_ses-1_run-1_T1w
Processing  sub-0003054
Converted successfully  data_mriqc/sub-0003054/ses-1/anat/sub-0003054_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-4_bold
Processing  sub-0003055
Converted successfully  data_mriqc/sub-0003055/ses-1/anat/sub-0003055_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-4_bold
Processing  sub-0003056
Converted successfully  data_mriqc/sub-0003056/ses-1/anat/sub-0003056_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-4_bold
Processing  sub-0003057
Converted successfully  data_mriqc/sub-0003057/ses-1/anat/sub-0003057_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-4_bold
Processing  sub-0003058
File not found  data_mriqc/sub-0003058/ses-1/anat/sub-0003058_ses-1_run-1_T1w
Processing  sub-0003059
Converted successfully  data_mriqc/sub-0003059/ses-1/anat/sub-0003059_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-4_bold
Processing  sub-0003060
Converted successfully  data_mriqc/sub-0003060/ses-1/anat/sub-0003060_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003060/ses-1/func/sub-0003060_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003060/ses-1/func/sub-0003060_ses-1_task-rest_run-2_bold
Processing  sub-0003061
Converted successfully  data_mriqc/sub-0003061/ses-1/anat/sub-0003061_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003061/ses-1/func/sub-0003061_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003061/ses-1/func/sub-0003061_ses-1_task-rest_run-2_bold
Processing  sub-0003062
Converted successfully  data_mriqc/sub-0003062/ses-1/anat/sub-0003062_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-3_bold

Converted successfully  data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-4_bold
Processing  sub-0003063
Converted successfully  data_mriqc/sub-0003063/ses-1/anat/sub-0003063_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-4_bold
Processing  sub-0003064
Converted successfully  data_mriqc/sub-0003064/ses-1/anat/sub-0003064_ses-1_run-1_T1w
Converted successfully  data_mriqc/sub-0003064/ses-1/func/sub-0003064_ses-1_task-rest_run-1_bold
Converted successfully  data_mriqc/sub-0003064/ses-1/func/sub-0003064_ses-1_task-rest_run-2_bold
Converted successfully  data_mriqc/sub-0003064/ses-1/func/sub-0003064_ses-1_task-rest_run-3_bold
Converted successfully  data_mriqc/sub-0003064/ses-1/func/sub-0003064_ses-1_task-rest_run-4_bold

In [107]:
nobrainer.io.read_csv(mriqc_data_path + '.csv')

[('bids_meta', '9:50'),
 ('cjv', '0.401860427832579'),
 ('cnr', '3.208961663420105'),
 ('efc', '0.580836820172799'),
 ('fber', '390.78839111328125'),
 ('fwhm_avg', '3.23895'),
 ('fwhm_x', '3.30307'),
 ('fwhm_y', '3.39808'),
 ('fwhm_z', '3.0157'),
 ('icvs_csf', '0.21052622519611203'),
 ('icvs_gm', '0.41061358646474905'),
 ('icvs_wm', '0.37886018833913704'),
 ('inu_med', '1.027437210083007'),
 ('inu_range', '0.42118954360485006'),
 ('provenance', ''),
 ('qi_1', '0'),
 ('qi_2', '0.000648464346346'),
 ('rpve_csf', '24.957280507145366'),
 ('rpve_gm', '13.17359122682958'),
 ('rpve_wm', '17.54493631724366'),
 ('size_x', '176'),
 ('size_y', '256'),
 ('size_z', '256'),
 ('snr_csf', '3.9359654288690282'),
 ('snr_gm', '9.789285026481359'),
 ('snr_total', '10.125599482528147'),
 ('snr_wm', '16.65154799223405'),
 ('snrd_csf', '17.52423162904197'),
 ('snrd_gm', '26.738537853122395'),
 ('snrd_total', '27.566998657696086'),
 ('snrd_wm', '38.43822649092389'),
 ('spacing_x', '1'),
 ('spacing_y', '1'),
 ('spacing_z', '1'),
 ('summary_bg_k', '1.321245247130718'),
 ('summary_bg_mad', '17.043880462646484'),
 ('summary_bg_mean', '29.145933151245117'),
 ('summary_bg_median', '26.312124252319336'),
 ('summary_bg_n', '2528987'),
 ('summary_bg_p05', '3.903988385200501'),
 ('summary_bg_p95', '63.88567886352538'),
 ('summary_bg_stdv', '18.4725284576416'),
 ('summary_csf_k', '0.651645957661372'),
 ('summary_csf_mad', '100.42141723632812'),
 ('summary_csf_mean', '441.40545654296875'),
 ('summary_csf_median', '455.9064636230469'),
 ('summary_csf_n', '6687'),
 ('summary_csf_p05', '225.27196960449217'),
 ('summary_csf_p95', '609.4790527343749'),
 ('summary_csf_stdv', '115.82225036621094'),
 ('summary_gm_k', '0.683671839711635'),
 ('summary_gm_mad', '64.60269165039062'),
 ('summary_gm_mean', '696.0536499023438'),
 ('summary_gm_median', '695.623779296875'),
 ('summary_gm_n', '14944'),
 ('summary_gm_p05', '579.3175811767578'),
 ('summary_gm_p95', '812.7630767822266'),
 ('summary_gm_stdv', '71.05733489990234'),
 ('summary_wm_k', '0.330666950067733'),
 ('summary_wm_mad', '57.71416473388672'),
 ('summary_wm_mean', '999.7518310546875'),
 ('summary_wm_median', '1000.000244140625'),
 ('summary_wm_n', '209520'),
 ('summary_wm_p05', '900.4823944091797'),
 ('summary_wm_p95', '1097.963952636719'),
 ('summary_wm_stdv', '60.05434799194336'),
 ('tpm_overlap_csf', '0.19428557157516402'),
 ('tpm_overlap_gm', '0.491109371185302'),
 ('tpm_overlap_wm', '0.5565974712371821'),
 ('wm2max', '0.49831004579299504')]

In [120]:
import csv

row_list = [['/home/doehlerj/Dokumente/brainhack2021/data_rawBIDS/BMB/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.nii.gz','/home/doehlerj/Dokumente/brainhack2021/data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.csv'],
           ['/home/doehlerj/Dokumente/brainhack2021/data_rawBIDS/BMB/sub-0003002/ses-1/anat/sub-0003002_ses-1_run-1_T1w.nii.gz','/home/doehlerj/Dokumente/brainhack2021/data_mriqc/sub-0003002/ses-1/anat/sub-0003002_ses-1_run-1_T1w.csv']]

filepaths_name = 'filepaths'

In [121]:
def paths_to_csv(filepaths_name,row_list):
    with open(filepaths_name + '.csv','w',newline='') as file:
        writer = csv.writer(file,delimiter=',')
        writer.writerows(row_list)

In [123]:
path_data = 'data_mriqc'
path_image = 'data_rawBIDS/BMB'

row_list_anat = []
row_list_func = []

for subj in subject_list:
    
    files = glob.glob(os.path.join(path_data,subj,session))
    
    if len(files) == 0:
        print('skip ', subj)
        continue
    
    print('Processing ', subj)
    session='ses-1'
    for mri in ['anat','func']:
        if mri == 'anat':
            csv_file_name = '{}_{}_run-1_T1w'.format(subj,session)
            csv_file = os.path.join(path_data,subj,session,mri,csv_file_name)
            image_file = os.path.join(path_image,subj,session,mri,csv_file_name)
            row_list_anat.append([image_file + '.nii.gz',csv_file + '.csv'])
        else:
            files = glob.glob(os.path.join(path_data,subj,session,mri)+'/*.json')
            for j in range(1,len(files)+1):
                csv_file_name = '{}_{}_task-rest_run-{}_bold'.format(subj,session,j)
                csv_file = os.path.join(path_data,subj,session,mri,csv_file_name)
                image_file = os.path.join(path_image,subj,session,mri,csv_file_name)
                row_list_func.append([image_file + '.nii.gz',csv_file + '.csv'])

Processing  sub-0003001
Processing  sub-0003002
skip  sub-0003003
Processing  sub-0003004
skip  sub-0003005
Processing  sub-0003006
Processing  sub-0003007
Processing  sub-0003008
Processing  sub-0003009
Processing  sub-0003010
Processing  sub-0003011
Processing  sub-0003012
Processing  sub-0003013
Processing  sub-0003014
Processing  sub-0003015
Processing  sub-0003016
Processing  sub-0003017
Processing  sub-0003018
skip  sub-0003019
Processing  sub-0003020
Processing  sub-0003021
Processing  sub-0003022
Processing  sub-0003023
Processing  sub-0003024
Processing  sub-0003025
Processing  sub-0003026
skip  sub-0003027
skip  sub-0003028
skip  sub-0003029
skip  sub-0003030
skip  sub-0003031
Processing  sub-0003032
Processing  sub-0003033
Processing  sub-0003034
skip  sub-0003035
skip  sub-0003036
Processing  sub-0003037
Processing  sub-0003038
Processing  sub-0003039
Processing  sub-0003040
Processing  sub-0003041
Processing  sub-0003042
skip  sub-0003043
Processing  sub-0003044
Processing  sub-0003045
skip  sub-0003046
Processing  sub-0003047
skip  sub-0003048
Processing  sub-0003049
Processing  sub-0003050
Processing  sub-0003051
Processing  sub-0003052
skip  sub-0003053
Processing  sub-0003054
Processing  sub-0003055
Processing  sub-0003056
Processing  sub-0003057
skip  sub-0003058
Processing  sub-0003059
Processing  sub-0003060
Processing  sub-0003061
Processing  sub-0003062
Processing  sub-0003063
Processing  sub-0003064

In [126]:
len(row_list_anat)

49

In [128]:
row_list_func

[['data_rawBIDS/BMB/sub-0003001/ses-1/func/sub-0003001_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003001/ses-1/func/sub-0003001_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003001/ses-1/func/sub-0003001_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003001/ses-1/func/sub-0003001_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003002/ses-1/func/sub-0003002_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003002/ses-1/func/sub-0003002_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003002/ses-1/func/sub-0003002_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003002/ses-1/func/sub-0003002_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003004/ses-1/func/sub-0003004_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003004/ses-1/func/sub-0003004_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003004/ses-1/func/sub-0003004_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003004/ses-1/func/sub-0003004_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003006/ses-1/func/sub-0003006_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003006/ses-1/func/sub-0003006_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003006/ses-1/func/sub-0003006_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003006/ses-1/func/sub-0003006_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003007/ses-1/func/sub-0003007_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003007/ses-1/func/sub-0003007_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003007/ses-1/func/sub-0003007_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003007/ses-1/func/sub-0003007_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003008/ses-1/func/sub-0003008_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003008/ses-1/func/sub-0003008_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003008/ses-1/func/sub-0003008_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003008/ses-1/func/sub-0003008_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003009/ses-1/func/sub-0003009_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003009/ses-1/func/sub-0003009_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003009/ses-1/func/sub-0003009_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003009/ses-1/func/sub-0003009_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003010/ses-1/func/sub-0003010_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003010/ses-1/func/sub-0003010_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003010/ses-1/func/sub-0003010_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003010/ses-1/func/sub-0003010_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003011/ses-1/func/sub-0003011_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003011/ses-1/func/sub-0003011_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003011/ses-1/func/sub-0003011_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003011/ses-1/func/sub-0003011_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003012/ses-1/func/sub-0003012_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003012/ses-1/func/sub-0003012_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003012/ses-1/func/sub-0003012_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003012/ses-1/func/sub-0003012_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003013/ses-1/func/sub-0003013_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003013/ses-1/func/sub-0003013_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003013/ses-1/func/sub-0003013_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003013/ses-1/func/sub-0003013_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003014/ses-1/func/sub-0003014_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003014/ses-1/func/sub-0003014_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003014/ses-1/func/sub-0003014_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003014/ses-1/func/sub-0003014_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003015/ses-1/func/sub-0003015_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003015/ses-1/func/sub-0003015_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003015/ses-1/func/sub-0003015_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003015/ses-1/func/sub-0003015_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003016/ses-1/func/sub-0003016_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003016/ses-1/func/sub-0003016_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003016/ses-1/func/sub-0003016_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003016/ses-1/func/sub-0003016_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003017/ses-1/func/sub-0003017_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003017/ses-1/func/sub-0003017_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003017/ses-1/func/sub-0003017_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003017/ses-1/func/sub-0003017_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003018/ses-1/func/sub-0003018_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003018/ses-1/func/sub-0003018_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003018/ses-1/func/sub-0003018_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003018/ses-1/func/sub-0003018_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003020/ses-1/func/sub-0003020_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003020/ses-1/func/sub-0003020_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003020/ses-1/func/sub-0003020_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003020/ses-1/func/sub-0003020_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003021/ses-1/func/sub-0003021_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003021/ses-1/func/sub-0003021_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003021/ses-1/func/sub-0003021_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003021/ses-1/func/sub-0003021_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003022/ses-1/func/sub-0003022_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003022/ses-1/func/sub-0003022_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003022/ses-1/func/sub-0003022_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003022/ses-1/func/sub-0003022_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003023/ses-1/func/sub-0003023_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003023/ses-1/func/sub-0003023_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003023/ses-1/func/sub-0003023_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003023/ses-1/func/sub-0003023_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003024/ses-1/func/sub-0003024_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003024/ses-1/func/sub-0003024_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003024/ses-1/func/sub-0003024_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003024/ses-1/func/sub-0003024_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003025/ses-1/func/sub-0003025_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003025/ses-1/func/sub-0003025_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003025/ses-1/func/sub-0003025_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003025/ses-1/func/sub-0003025_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003026/ses-1/func/sub-0003026_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003026/ses-1/func/sub-0003026_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003026/ses-1/func/sub-0003026_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003026/ses-1/func/sub-0003026_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003032/ses-1/func/sub-0003032_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003032/ses-1/func/sub-0003032_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003032/ses-1/func/sub-0003032_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003032/ses-1/func/sub-0003032_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003033/ses-1/func/sub-0003033_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003033/ses-1/func/sub-0003033_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003033/ses-1/func/sub-0003033_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003033/ses-1/func/sub-0003033_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003034/ses-1/func/sub-0003034_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003034/ses-1/func/sub-0003034_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003034/ses-1/func/sub-0003034_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003034/ses-1/func/sub-0003034_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003037/ses-1/func/sub-0003037_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003037/ses-1/func/sub-0003037_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003037/ses-1/func/sub-0003037_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003037/ses-1/func/sub-0003037_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003038/ses-1/func/sub-0003038_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003038/ses-1/func/sub-0003038_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003038/ses-1/func/sub-0003038_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003038/ses-1/func/sub-0003038_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003039/ses-1/func/sub-0003039_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003039/ses-1/func/sub-0003039_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003039/ses-1/func/sub-0003039_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003039/ses-1/func/sub-0003039_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003040/ses-1/func/sub-0003040_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003040/ses-1/func/sub-0003040_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003040/ses-1/func/sub-0003040_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003040/ses-1/func/sub-0003040_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003041/ses-1/func/sub-0003041_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003041/ses-1/func/sub-0003041_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003041/ses-1/func/sub-0003041_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003041/ses-1/func/sub-0003041_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003042/ses-1/func/sub-0003042_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003042/ses-1/func/sub-0003042_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003042/ses-1/func/sub-0003042_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003042/ses-1/func/sub-0003042_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003044/ses-1/func/sub-0003044_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003044/ses-1/func/sub-0003044_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003044/ses-1/func/sub-0003044_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003044/ses-1/func/sub-0003044_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003045/ses-1/func/sub-0003045_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003045/ses-1/func/sub-0003045_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003045/ses-1/func/sub-0003045_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003045/ses-1/func/sub-0003045_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003047/ses-1/func/sub-0003047_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003047/ses-1/func/sub-0003047_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003047/ses-1/func/sub-0003047_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003047/ses-1/func/sub-0003047_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003049/ses-1/func/sub-0003049_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003049/ses-1/func/sub-0003049_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003049/ses-1/func/sub-0003049_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003049/ses-1/func/sub-0003049_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003050/ses-1/func/sub-0003050_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003050/ses-1/func/sub-0003050_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003050/ses-1/func/sub-0003050_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003050/ses-1/func/sub-0003050_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003051/ses-1/func/sub-0003051_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003052/ses-1/func/sub-0003052_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003054/ses-1/func/sub-0003054_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003055/ses-1/func/sub-0003055_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003056/ses-1/func/sub-0003056_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003057/ses-1/func/sub-0003057_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003059/ses-1/func/sub-0003059_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003060/ses-1/func/sub-0003060_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003060/ses-1/func/sub-0003060_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003060/ses-1/func/sub-0003060_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003060/ses-1/func/sub-0003060_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003061/ses-1/func/sub-0003061_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003061/ses-1/func/sub-0003061_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003061/ses-1/func/sub-0003061_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003061/ses-1/func/sub-0003061_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003062/ses-1/func/sub-0003062_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-1_bold.nii.gz',
  'data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-1_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-2_bold.nii.gz',
  'data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-2_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-3_bold.nii.gz',
  'data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-3_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-4_bold.nii.gz',
  'data_mriqc/sub-0003063/ses-1/func/sub-0003063_ses-1_task-rest_run-4_bold.csv'],
 ['data_rawBIDS/BMB/sub-0003064/ses-1/func/sub-0003064_ses-1_task-rest_run-1_bold.nii.gz',

In [144]:
filepaths_anat = 'filepaths_anat'
filepaths_func = 'filepaths_func'

paths_to_csv(filepaths_anat,row_list_anat)
paths_to_csv(filepaths_func,row_list_func)

In [156]:
df_row_list_anat = pd.DataFrame(row_list_anat,columns=['features','labels'])
df_row_list_anat = df_row_list_anat.reset_index(drop=True)

df_row_list_func = pd.DataFrame(row_list_func,columns=['features','labels'])
df_row_list_func = df_row_list_func.reset_index(drop=True)

In [154]:
df_row_list_anat

,features,labels
0,data_rawBIDS/BMB/sub-0003001/ses-1/anat/sub-00...,data_mriqc/sub-0003001/ses-1/anat/sub-0003001_...
1,data_rawBIDS/BMB/sub-0003002/ses-1/anat/sub-00...,data_mriqc/sub-0003002/ses-1/anat/sub-0003002_...
2,data_rawBIDS/BMB/sub-0003004/ses-1/anat/sub-00...,data_mriqc/sub-0003004/ses-1/anat/sub-0003004_...
3,data_rawBIDS/BMB/sub-0003006/ses-1/anat/sub-00...,data_mriqc/sub-0003006/ses-1/anat/sub-0003006_...
4,data_rawBIDS/BMB/sub-0003007/ses-1/anat/sub-00...,data_mriqc/sub-0003007/ses-1/anat/sub-0003007_...
5,data_rawBIDS/BMB/sub-0003008/ses-1/anat/sub-00...,data_mriqc/sub-0003008/ses-1/anat/sub-0003008_...
6,data_rawBIDS/BMB/sub-0003009/ses-1/anat/sub-00...,data_mriqc/sub-0003009/ses-1/anat/sub-0003009_...
7,data_rawBIDS/BMB/sub-0003010/ses-1/anat/sub-00...,data_mriqc/sub-0003010/ses-1/anat/sub-0003010_...
8,data_rawBIDS/BMB/sub-0003011/ses-1/anat/sub-00...,data_mriqc/sub-0003011/ses-1/anat/sub-0003011_...
9,data_rawBIDS/BMB/sub-0003012/ses-1/anat/sub-00...,data_mriqc/sub-0003012/ses-1/anat/sub-0003012_...
10,data_rawBIDS/BMB/sub-0003013/ses-1/anat/sub-00...,data_mriqc/sub-0003013/ses-1/anat/sub-0003013_...
11,data_rawBIDS/BMB/sub-0003014/ses-1/anat/sub-00...,data_mriqc/sub-0003014/ses-1/anat/sub-0003014_...
12,data_rawBIDS/BMB/sub-0003015/ses-1/anat/sub-00...,data_mriqc/sub-0003015/ses-1/anat/sub-0003015_...
13,data_rawBIDS/BMB/sub-0003016/ses-1/anat/sub-00...,data_mriqc/sub-0003016/ses-1/anat/sub-0003016_...
14,data_rawBIDS/BMB/sub-0003017/ses-1/anat/sub-00...,data_mriqc/sub-0003017/ses-1/anat/sub-0003017_...
15,data_rawBIDS/BMB/sub-0003018/ses-1/anat/sub-00...,data_mriqc/sub-0003018/ses-1/anat/sub-0003018_...
16,data_rawBIDS/BMB/sub-0003020/ses-1/anat/sub-00...,data_mriqc/sub-0003020/ses-1/anat/sub-0003020_...
17,data_rawBIDS/BMB/sub-0003021/ses-1/anat/sub-00...,data_mriqc/sub-0003021/ses-1/anat/sub-0003021_...
18,data_rawBIDS/BMB/sub-0003022/ses-1/anat/sub-00...,data_mriqc/sub-0003022/ses-1/anat/sub-0003022_...
19,data_rawBIDS/BMB/sub-0003023/ses-1/anat/sub-00...,data_mriqc/sub-0003023/ses-1/anat/sub-0003023_...
20,data_rawBIDS/BMB/sub-0003024/ses-1/anat/sub-00...,data_mriqc/sub-0003024/ses-1/anat/sub-0003024_...
21,data_rawBIDS/BMB/sub-0003025/ses-1/anat/sub-00...,data_mriqc/sub-0003025/ses-1/anat/sub-0003025_...
22,data_rawBIDS/BMB/sub-0003026/ses-1/anat/sub-00...,data_mriqc/sub-0003026/ses-1/anat/sub-0003026_...
23,data_rawBIDS/BMB/sub-0003032/ses-1/anat/sub-00...,data_mriqc/sub-0003032/ses-1/anat/sub-0003032_...
24,data_rawBIDS/BMB/sub-0003033/ses-1/anat/sub-00...,data_mriqc/sub-0003033/ses-1/anat/sub-0003033_...
25,data_rawBIDS/BMB/sub-0003034/ses-1/anat/sub-00...,data_mriqc/sub-0003034/ses-1/anat/sub-0003034_...
26,data_rawBIDS/BMB/sub-0003037/ses-1/anat/sub-00...,data_mriqc/sub-0003037/ses-1/anat/sub-0003037_...
27,data_rawBIDS/BMB/sub-0003038/ses-1/anat/sub-00...,data_mriqc/sub-0003038/ses-1/anat/sub-0003038_...
28,data_rawBIDS/BMB/sub-0003039/ses-1/anat/sub-00...,data_mriqc/sub-0003039/ses-1/anat/sub-0003039_...
29,data_rawBIDS/BMB/sub-0003040/ses-1/anat/sub-00...,data_mriqc/sub-0003040/ses-1/anat/sub-0003040_...
30,data_rawBIDS/BMB/sub-0003041/ses-1/anat/sub-00...,data_mriqc/sub-0003041/ses-1/anat/sub-0003041_...
31,data_rawBIDS/BMB/sub-0003042/ses-1/anat/sub-00...,data_mriqc/sub-0003042/ses-1/anat/sub-0003042_...
32,data_rawBIDS/BMB/sub-0003044/ses-1/anat/sub-00...,data_mriqc/sub-0003044/ses-1/anat/sub-0003044_...
33,data_rawBIDS/BMB/sub-0003045/ses-1/anat/sub-00...,data_mriqc/sub-0003045/ses-1/anat/sub-0003045_...
34,data_rawBIDS/BMB/sub-0003047/ses-1/anat/sub-00...,data_mriqc/sub-0003047/ses-1/anat/sub-0003047_...
35,data_rawBIDS/BMB/sub-0003049/ses-1/anat/sub-00...,data_mriqc/sub-0003049/ses-1/anat/sub-0003049_...
36,data_rawBIDS/BMB/sub-0003050/ses-1/anat/sub-00...,data_mriqc/sub-0003050/ses-1/anat/sub-0003050_...
37,data_rawBIDS/BMB/sub-0003051/ses-1/anat/sub-00...,data_mriqc/sub-0003051/ses-1/anat/sub-0003051_...
38,data_rawBIDS/BMB/sub-0003052/ses-1/anat/sub-00...,data_mriqc/sub-0003052/ses-1/anat/sub-0003052_...
39,data_rawBIDS/BMB/sub-0003054/ses-1/anat/sub-00...,data_mriqc/sub-0003054/ses-1/anat/sub-0003054_...
40,data_rawBIDS/BMB/sub-0003055/ses-1/anat/sub-00...,data_mriqc/sub-0003055/ses-1/anat/sub-0003055_...
41,data_rawBIDS/BMB/sub-0003056/ses-1/anat/sub-00...,data_mriqc/sub-0003056/ses-1/anat/sub-0003056_...
42,data_rawBIDS/BMB/sub-0003057/ses-1/anat/sub-00...,data_mriqc/sub-0003057/ses-1/anat/sub-0003057_...
43,data_rawBIDS/BMB/sub-0003059/ses-1/anat/sub-00...,data_mriqc/sub-0003059/ses-1/anat/sub-0003059_...
44,data_rawBIDS/BMB/sub-0003060/ses-1/anat/sub-00...,data_mriqc/sub-0003060/ses-1/anat/sub-0003060_...
45,data_rawBIDS/BMB/sub-0003061/ses-1/anat/sub-00...,data_mriqc/sub-0003061/ses-1/anat/sub-0003061_...
46,data_rawBIDS/BMB/sub-0003062/ses-1/anat/sub-00...,data_mriqc/sub-0003062/ses-1/anat/sub-0003062_...
47,data_rawBIDS/BMB/sub-0003063/ses-1/anat/sub-00...,data_mriqc/sub-0003063/ses-1/anat/sub-0003063_...
48,data_rawBIDS/BMB/sub-0003064/ses-1/anat/sub-00...,data_mriqc/sub-0003064/ses-1/anat/sub-0003064_...

In [159]:
df_row_list_func

,features,labels
0,data_rawBIDS/BMB/sub-0003001/ses-1/func/sub-00...,data_mriqc/sub-0003001/ses-1/func/sub-0003001_...
1,data_rawBIDS/BMB/sub-0003001/ses-1/func/sub-00...,data_mriqc/sub-0003001/ses-1/func/sub-0003001_...
2,data_rawBIDS/BMB/sub-0003002/ses-1/func/sub-00...,data_mriqc/sub-0003002/ses-1/func/sub-0003002_...
3,data_rawBIDS/BMB/sub-0003002/ses-1/func/sub-00...,data_mriqc/sub-0003002/ses-1/func/sub-0003002_...
4,data_rawBIDS/BMB/sub-0003004/ses-1/func/sub-00...,data_mriqc/sub-0003004/ses-1/func/sub-0003004_...
...,...,...
113,data_rawBIDS/BMB/sub-0003063/ses-1/func/sub-00...,data_mriqc/sub-0003063/ses-1/func/sub-0003063_...
114,data_rawBIDS/BMB/sub-0003064/ses-1/func/sub-00...,data_mriqc/sub-0003064/ses-1/func/sub-0003064_...
115,data_rawBIDS/BMB/sub-0003064/ses-1/func/sub-00...,data_mriqc/sub-0003064/ses-1/func/sub-0003064_...
116,data_rawBIDS/BMB/sub-0003064/ses-1/func/sub-00...,data_mriqc/sub-0003064/ses-1/func/sub-0003064_...
117,data_rawBIDS/BMB/sub-0003064/ses-1/func/sub-00...,data_mriqc/sub-0003064/ses-1/func/sub-0003064_...

In [163]:
filepaths_anat = 'filepaths_anat'
filepaths_func = 'filepaths_func'

df_row_list_anat.to_csv(filepaths_anat + '.csv',index=False)
df_row_list_func.to_csv(filepaths_func + '.csv',index=False)

In [134]:
!nobrainer convert --help

2021-06-18 14:30:39.962199: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/doehlerj/lipsia/lib:/home/doehlerj/lipsia-master/lib:#Lipsia
2021-06-18 14:30:39.962227: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/tensorflow_probability/python/internal/variadic_reduce.py:115: calling function (from tensorflow.python.eager.def_function) with experimental_compile is deprecated and will be removed in a future version.
Instructions for updating:
experimental_compile is deprecated, use jit_compile instead
Usage: nobrainer convert [OPTIONS]

  Convert medical imaging volumes to TFRecords.

  Volumes must all be the same shape. This will overwrite existing TFRecord
  files.

  Labels can be volumetric or scalar.

Options:
  -c, --csv PATH                  [required]
  -t, --tfrecords-template TEXT   [default: tfrecords/data_shard-{shard:03d}.t
                                  frec;required]
  -s, --volume-shape INTEGER...   [required]
  -n, --examples-per-shard INTEGER
                                  Number of (feature, label) pairs per
                                  TFRecord file.  [default: 100]
  --to-ras / --no-to-ras          Reorient volumes to RAS before saving to
                                  TFRecords.  [default: to-ras]
  --gzip / --no-gzip              Compress TFRecords with gzip (highly
                                  recommended).  [default: gzip]
  --verify-volumes / --no-verify-volumes
                                  Verify volume pairs before converting. This
                                  option is highly recommended, as it checks
                                  that shapes of features and labels are equal
                                  to "volume-shape", that labels are (or can
                                  safely be coerced to) an integer type, and
                                  that labels are all >= 0.  [default: verify-
                                  volumes]
  -j, --num-parallel-calls INTEGER
                                  Number of processes to use. If -1, uses all
                                  available processes.  [default: -1]
  -v, --verbose                   Print progress bar.  [default: False]
  --help                          Show this message and exit.

In [164]:
!mkdir -p data_tfrec

In [170]:
filepaths = nobrainer.io.read_csv('filepaths_anat.csv')

In [171]:
alid = nobrainer.io.verify_features_labels(filepaths)

Verifying 49 examples
 0/49 [..............................] - ETA: 0s

ImageFileError: Cannot work out file type of "data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.csv"

In [168]:
filepaths

[('data_rawBIDS/BMB/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003002/ses-1/anat/sub-0003002_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003002/ses-1/anat/sub-0003002_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003004/ses-1/anat/sub-0003004_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003004/ses-1/anat/sub-0003004_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003006/ses-1/anat/sub-0003006_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003006/ses-1/anat/sub-0003006_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003007/ses-1/anat/sub-0003007_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003007/ses-1/anat/sub-0003007_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003008/ses-1/anat/sub-0003008_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003008/ses-1/anat/sub-0003008_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003009/ses-1/anat/sub-0003009_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003009/ses-1/anat/sub-0003009_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003010/ses-1/anat/sub-0003010_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003010/ses-1/anat/sub-0003010_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003011/ses-1/anat/sub-0003011_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003011/ses-1/anat/sub-0003011_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003012/ses-1/anat/sub-0003012_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003012/ses-1/anat/sub-0003012_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003013/ses-1/anat/sub-0003013_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003013/ses-1/anat/sub-0003013_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003014/ses-1/anat/sub-0003014_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003014/ses-1/anat/sub-0003014_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003015/ses-1/anat/sub-0003015_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003015/ses-1/anat/sub-0003015_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003016/ses-1/anat/sub-0003016_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003016/ses-1/anat/sub-0003016_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003017/ses-1/anat/sub-0003017_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003017/ses-1/anat/sub-0003017_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003018/ses-1/anat/sub-0003018_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003018/ses-1/anat/sub-0003018_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003020/ses-1/anat/sub-0003020_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003020/ses-1/anat/sub-0003020_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003021/ses-1/anat/sub-0003021_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003021/ses-1/anat/sub-0003021_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003022/ses-1/anat/sub-0003022_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003022/ses-1/anat/sub-0003022_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003023/ses-1/anat/sub-0003023_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003023/ses-1/anat/sub-0003023_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003024/ses-1/anat/sub-0003024_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003024/ses-1/anat/sub-0003024_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003025/ses-1/anat/sub-0003025_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003025/ses-1/anat/sub-0003025_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003026/ses-1/anat/sub-0003026_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003026/ses-1/anat/sub-0003026_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003032/ses-1/anat/sub-0003032_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003032/ses-1/anat/sub-0003032_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003033/ses-1/anat/sub-0003033_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003033/ses-1/anat/sub-0003033_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003034/ses-1/anat/sub-0003034_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003034/ses-1/anat/sub-0003034_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003037/ses-1/anat/sub-0003037_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003037/ses-1/anat/sub-0003037_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003038/ses-1/anat/sub-0003038_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003038/ses-1/anat/sub-0003038_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003039/ses-1/anat/sub-0003039_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003039/ses-1/anat/sub-0003039_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003040/ses-1/anat/sub-0003040_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003040/ses-1/anat/sub-0003040_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003041/ses-1/anat/sub-0003041_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003041/ses-1/anat/sub-0003041_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003042/ses-1/anat/sub-0003042_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003042/ses-1/anat/sub-0003042_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003044/ses-1/anat/sub-0003044_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003044/ses-1/anat/sub-0003044_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003045/ses-1/anat/sub-0003045_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003045/ses-1/anat/sub-0003045_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003047/ses-1/anat/sub-0003047_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003047/ses-1/anat/sub-0003047_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003049/ses-1/anat/sub-0003049_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003049/ses-1/anat/sub-0003049_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003050/ses-1/anat/sub-0003050_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003050/ses-1/anat/sub-0003050_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003051/ses-1/anat/sub-0003051_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003051/ses-1/anat/sub-0003051_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003052/ses-1/anat/sub-0003052_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003052/ses-1/anat/sub-0003052_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003054/ses-1/anat/sub-0003054_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003054/ses-1/anat/sub-0003054_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003055/ses-1/anat/sub-0003055_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003055/ses-1/anat/sub-0003055_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003056/ses-1/anat/sub-0003056_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003056/ses-1/anat/sub-0003056_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003057/ses-1/anat/sub-0003057_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003057/ses-1/anat/sub-0003057_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003059/ses-1/anat/sub-0003059_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003059/ses-1/anat/sub-0003059_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003060/ses-1/anat/sub-0003060_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003060/ses-1/anat/sub-0003060_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003061/ses-1/anat/sub-0003061_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003061/ses-1/anat/sub-0003061_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003062/ses-1/anat/sub-0003062_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003062/ses-1/anat/sub-0003062_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003063/ses-1/anat/sub-0003063_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003063/ses-1/anat/sub-0003063_ses-1_run-1_T1w.csv'),
 ('data_rawBIDS/BMB/sub-0003064/ses-1/anat/sub-0003064_ses-1_run-1_T1w.nii.gz',
  'data_mriqc/sub-0003064/ses-1/anat/sub-0003064_ses-1_run-1_T1w.csv')]

In [161]:
!nobrainer convert \
    --csv='filepaths_anat.csv' \
    --tfrecords-template='data_tfrec/data_shard-{shard:03d}.tfrec' \
    --examples-per-shard=5 \
    --volume-shape 176 256 256 \
    --verbose

2021-06-18 15:41:34.048908: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/doehlerj/lipsia/lib:/home/doehlerj/lipsia-master/lib:#Lipsia
2021-06-18 15:41:34.048989: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From /home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/tensorflow_probability/python/internal/variadic_reduce.py:115: calling function (from tensorflow.python.eager.def_function) with experimental_compile is deprecated and will be removed in a future version.
Instructions for updating:
experimental_compile is deprecated, use jit_compile instead
Verifying 49 examples
 0/49 [..............................] - ETA: 0smultiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/nobrainer/io.py", line 145, in _verify_features_nonscalar_labels
    y = nib.load(pair_of_paths[1])
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/nibabel/loadsave.py", line 55, in load
    raise ImageFileError(f'Cannot work out file type of "{filename}"')
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.csv"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/bin/nobrainer", line 8, in <module>
    sys.exit(cli())
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/nobrainer/cli/main.py", line 134, in convert
    invalid_pairs = _verify_features_labels(
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/site-packages/nobrainer/io.py", line 131, in verify_features_labels
    for valid in p.imap(map_fn, volume_filepaths, chunksize=2):
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/multiprocessing/pool.py", line 420, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/doehlerj/anaconda3/envs/brainhack_auto-qc/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "data_mriqc/sub-0003001/ses-1/anat/sub-0003001_ses-1_run-1_T1w.csv"